// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euqkgsjlqqnsjplhgwpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cWtnc2pscXFuc2pwbGhnd3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODM0NzgsImV4cCI6MjA3MDY1OTQ3OH0.nQOqO1TTX-63L5iQL0ajpznPx0KTXkVANM75MojKQn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});